import Image from "next/image";
import { Plus, Trash2 } from "lucide-react";
import { createCategory, deleteCategory, updateCategory } from "@/app/admin/actions";
import { Notice, PageHeader } from "@/components/admin/page-header";
import { Button } from "@/components/ui/button";
import { Input, Textarea } from "@/components/ui/input";
import { db } from "@/lib/store-db";

type SearchParams = Promise<{ saved?: string; deleted?: string }>;
export const dynamic = "force-dynamic";

export default async function CategoriesPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const categories = await db.category.findMany({ include: { _count: { select: { products: true } } }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }] });
  return <><PageHeader title="Категории" text="Структура каталога и визуальные обложки категорий." /><Notice type={params.deleted ? "deleted" : params.saved ? "saved" : undefined} />
    <details className="mb-6 rounded-[1.5rem] border border-black/10 bg-white/75 p-5 open:pb-7"><summary className="flex cursor-pointer list-none items-center gap-2 text-sm font-medium"><Plus className="h-4 w-4" /> Добавить категорию</summary><form action={createCategory} className="mt-6 grid gap-4 md:grid-cols-2"><Input name="name" required placeholder="Название" /><Input name="slug" placeholder="Slug (необязательно)" /><Input name="image" placeholder="URL изображения или загрузите файл" /><Input type="file" name="imageFile" accept="image/*" className="h-auto py-3" /><Input type="number" name="sortOrder" defaultValue="0" placeholder="Порядок" /><label className="flex items-center gap-3 rounded-xl border border-black/10 bg-white px-4 text-sm"><input type="checkbox" name="isActive" defaultChecked /> Активна</label><Textarea name="description" placeholder="Описание" className="md:col-span-2" /><Button className="md:col-span-2">Создать категорию</Button></form></details>
    <div className="grid gap-4 xl:grid-cols-2">{categories.map((category: import("@/lib/types").Category & { _count: { products: number } }) => <details key={category.id} className="rounded-[1.5rem] border border-black/10 bg-white/75 p-5 open:pb-6"><summary className="grid cursor-pointer list-none grid-cols-[72px_1fr_auto] items-center gap-4"><div className="relative h-16 w-16 overflow-hidden rounded-xl bg-[#eee]"><Image src={category.image || "/media/lookbook-men.webp"} alt={category.name} fill className="object-cover" /></div><div><h2 className="font-display text-3xl tracking-[-0.035em]">{category.name}</h2><p className="mt-1 text-xs text-black/40">/{category.slug} · {category._count.products} товаров</p></div><span className="text-xs text-black/40">Редактировать</span></summary><form action={updateCategory} className="mt-6 grid gap-4 border-t border-black/10 pt-6 sm:grid-cols-2"><input type="hidden" name="id" value={category.id} /><Input name="name" required defaultValue={category.name} /><Input name="slug" defaultValue={category.slug} /><Input name="image" defaultValue={category.image} /><Input type="file" name="imageFile" accept="image/*" className="h-auto py-3" /><Input type="number" name="sortOrder" defaultValue={category.sortOrder} /><label className="flex items-center gap-3 rounded-xl border border-black/10 bg-white px-4 text-sm"><input type="checkbox" name="isActive" defaultChecked={category.isActive} /> Активна</label><Textarea name="description" defaultValue={category.description} className="sm:col-span-2" /><Button className="sm:col-span-2">Сохранить</Button></form><form action={deleteCategory} className="mt-3"><input type="hidden" name="id" value={category.id} /><button className="flex items-center gap-2 text-xs text-red-600"><Trash2 className="h-4 w-4" /> Удалить категорию</button></form></details>)}</div>
  </>;
}
